# 数据库连接信息
spring:
    datasource:
        # 驱动类名称
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 数据库连接的URL
        url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&useAffectedRows=true&serverTimezone=UTC
        # 用户名
        username: root
        # 密码
        password: Cxdmysql20251227
    servlet:
        multipart:
            max-file-size: -1
            max-request-size: -1

# MyBatis配置信息
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true

server:
    tomcat:
        max-http-form-post-size: -1